version: "3.7"
services:
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:3000"
    environment:
      REDIS_HOST_URL: redis://redis:6379
    restart: unless-stopped
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    restart: unless-stopped
