version: "3.7"
services:
  app:
    build: .
    depends_on:
      - redis
    networks:
      - nginx
    restart: unless-stopped
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    restart: unless-stopped
