# next js + redis
version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:alpine
      - ./data:/data
    restart: unless-stopped

